### ISSUE TITLE
HMS_0700_2000_0003_0002 error in bambu handy cannot be cleared without turning P1S off 

### ISSUE THREAD

**Issue by ThorsReign** [bambulab/Bambu-Handy#136]
When printing using filament backup on the AMS, Bambu Handy will display a user friendly error to translate HMS_0700_2000_0003_0002 to "AMS1 Slot1 filament has run out and automatically switched to the slot with the same filament."

This message will not clear from Bambu Handy's device tab or the Machine Assistant portion of settings until the printer is reset, regardless of the number of prints you run since then, or adding new filament to the slot.  Irritating bug when the app is telling you that slot 1 ran out when you're actively printing from slot 1.

**Comment by sodachen22** [comment]
@ThorsReign Does this problem always existed and what is the type of the printer, X1 or P1? If it is a ramdon issue, the reason could be the network is not stable enough. If this issue persists, please create a ticket and share the log.

**Comment by ThorsReign** [comment]
I forgot I opened this.  It's resolved as of the 1.04.02 firmware update

**Comment by ThorsReign** [comment]
Resolved with latest firmware

**Comment by BradysFidgets** [comment]
Not resolved. P1S/AMS, firmware 1.05.02. Having the exact same issue.

**Comment by solsystemlabs** [comment]
Same here. Seems like this bug got reintroduced.

**Comment by mroek** [comment]
I'm also seeing this on the X1C. Latest official firmware and Handy.

**Comment by felipecabargas** [comment]
Seeing this on P1S on latest firmware (01.06.01.02)

**Comment by Landona24** [comment]
> I forgot I opened this. It's resolved as of the 1.04.02 firmware update

This issue is not resolved on the X1E either on 01.01.02.00.
